[sdl]
fullscreen=false
output=opengl
windowresolution=1024x768

[dosbox]
machine=svga_s3
memsize=16

[render]
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=486
cycles=max

[autoexec]
@echo off
mount c ~/dev/01_labs/caalp/asm
c:
cd knights-quest\src
prompt $p$g
cls
echo ====================================
echo  KNIGHT'S QUEST DEVELOPMENT ENV
echo ====================================
echo.
echo Type: BUILD filename (to compile)
echo Type: cd .. (to go back)
echo.
